version: 2

build:

  os: ubuntu-22.04

  tools:
    python: "3.9"

  jobs:
    pre_build:
      - rm -rf ./docs/apidoc
      - pdoc checkpointing -o ./docs/apidoc --docformat google

python:
  install:
    - requirements: dev-requirements.txt
    - requirements: requirements.txt

mkdocs:
  configuration: mkdocs.yml
