version: 2

build:

  os: ubuntu-22.04

  tools:
    python: "3.9"

  jobs:

    pre_install:
      - pip install -r dev-requirements.txt
      - pip install -r requirements.txt

    pre_build:
      - rm -rf ./docs/apidoc
      - pdoc checkpointing -o ./docs/apidoc --docformat google

mkdocs:
  configuration: mkdocs.yml
