site_name: checkpointing

theme:
  name: material

nav:
  - "User Guide": index.md
  - "Behavior on Code Change": behavior.md
  - "Caveats": caveats.md
  - "Comparison with Alternatives": comparison.md
  - "Extending the Checkpoint": extension.md
  - "Changelog": changelog.md
  - "API Reference": apidoc/index.html" target="_blank

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.details
  - attr_list

repo_url: https://github.com/Vopaaz/checkpointing
repo_name: Vopaaz/checkpointing
