site_name: checkpointing

theme:
  name: material

nav:
  - "User Guide": index.md
  - "Behavior on Code Change": behavior.md
  - "Known Caveats": caveats.md
  - "Comparison with Similar Packages": comparison.md

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/highlight.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
