site_name: Documentation - checkpointing

theme:
  name: readthedocs

nav:
  - "User Guide": index.md
  - "Cases when function is skipped/re-executed": cases.md
  - "Comparison with similar packages": comparison.md

markdown_extensions:
  - footnotes
  - admonition
