site_name: Documentation - checkpointing

theme:
  name: readthedocs

nav:
  - "User Guide": index.md
  - "Use Cases": cases.md
  - "Known Caveats": caveats.md
  - "Comparison with Similar Packages": comparison.md

markdown_extensions:
  - footnotes
  - admonition
