name: Deploy the API docs

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Build website
        run: pdoc checkpointing -o ./apidoc --docformat google

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apidoc
