name: Unit Testing on Merge or commit to master

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        runs-on: ["ubuntu-latest", "windows-latest", "macos-latest"]

    runs-on: "${{ matrix.runs-on }}"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Run tests
        run: nosetests --with-coverage --cover-xml --cover-package=checkpointing --with-doctest tests/**/*.py checkpointing/**/*.py

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
