name: Testing on Master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        runs-on: ["ubuntu-latest", "windows-latest", "macos-latest"]

    runs-on: "${{ matrix.runs-on }}"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Run unit tests
        run: pytest tests/ checkpointing/

      - name: Run integration tests
        run: python -m integtests.run --wait-sec 0.5

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
