name: Testing on Master

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

  pull_request:
    branches:
      - master

jobs:
  build:

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    # Ubuntu is tested on all pushes
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install -r requirements.txt

      - name: Install comparison dependencies
        if: ${{ matrix.python-version != '3.12' }}
        run: |
          pip install -r comparison-requirements.txt

      - name: Run unit tests
        run: pytest tests/ checkpointing/

      - name: Run integration tests
        if: ${{ matrix.python-version }} != '3.12'
        run: python -m integtests.run --wait-sec 3

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./.coverage/.xml-coverage
