name: Unit Testing

on:
  push:
    branches-ignore:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Manual tests for synchronized cache
        run: python -m tests.cache.synchronization_test.py

      - name: Run tests
        run: nosetests --with-coverage --cover-xml --cover-package=checkpointing --with-doctest tests/**/*.py checkpointing/**/*.py

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
